/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject2;

import java.text.DecimalFormat;
import java.util.Locale;

/**
 *
 * @author Aluno
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }
    String de,para;
    Double saida;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num = new javax.swing.JTextField();
        varDe = new javax.swing.JComboBox<>();
        resultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        varPara = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        varDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quilômetro", "Metro", "Decímetro", "Centímetro", "Milímetro" }));

        resultado.setText("          Resultado");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        varPara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quilômetro", "Metro", "Decímetro", "Centímetro", "Milímetro" }));

        jLabel2.setText("De");

        jLabel3.setText("Para");

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(varPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(31, 31, 31)
                .addComponent(resultado)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        de = varDe.getSelectedItem().toString();
        para = varPara.getSelectedItem().toString();
        Double numero =  Double.parseDouble(num.getText()); 
      
        switch(de)
        {
            case "Quilômetro":
                if(para == "Metro"){
                   saida= numero*1000.0;
                }else 
                if(para == "Decímetro"){
                   saida= (numero*1000.0)*10.0; 
                }else
                if(para == "Centímetro"){
                   saida= (numero*1000.0)*100.0; 
                }else
                if(para == "Milímetro"){
                   saida= numero*1000.0*1000.0; 
                }
                else
                if(para == "Quilômetro"){
                   saida= numero; 
                }
                break;
            case "Metro":
                if(para == "Quilômetro"){
                   saida= numero/1000.0;
                }else 
                if(para == "Decímetro"){
                   saida= (numero)*10.0; 
                }else
                if(para == "Centímetro"){
                   saida= (numero)*100.0; 
                }else
                if(para == "Milímetro"){
                   saida= numero*1000.0; 
                }
                                else
                if(para == "Metro"){
                   saida= numero; 
                }
                break;
            case "Decímetro":
                if(para == "Metro"){
                   saida= numero/10.0;
                }else 
                if(para == "Quilômetro"){
                   saida= (numero/10000.0); 
                }else
                if(para == "Centímetro"){
                   saida= numero*10.0; 
                }else
                if(para == "Milímetro"){
                   saida= numero*100.0; 
                }
                else
                if(para == "Decímetro"){
                   saida= numero; 
                }
                break;
            case "Centímetro":
                if(para == "Metro"){
                   saida= numero/100.0;
                }else 
                if(para == "Decímetro"){
                   saida= numero/10.0; 
                }else
                if(para == "Quilômetro"){
                   saida= (numero/1000.0); 
                }else
                if(para == "Milímetro"){
                   saida= numero*10.0; 
                }
                else
                if(para == "Centímetro"){
                   saida= numero; 
                }
                break;
            case "Milímetro":
                if(para == "Metro"){
                   saida= numero*1000.0;
                }else 
                if(para == "Decímetro"){
                   saida= numero*100.0; 
                }else
                if(para == "Centímetro"){
                   saida= numero*10.0; 
                }else
                if(para == "Quilômetro"){
                   saida= numero*10000.0; 
                }
                else
                if(para == "Milímetro"){
                   saida= numero; 
                }
                break;
                
        }
        Locale locale = new Locale("en","US");
        Locale.setDefault(locale);
        DecimalFormat decimalFormat = new DecimalFormat("#.#######");
        String result = decimalFormat.format(saida);
        String unidade= "";
        switch(para){
            case "Quilômetro":
                unidade = " km";
                break;
            case "Metro":
                unidade = " m";
                break;
            case "Decímetro":
                unidade = " dm";
                break;
            case "Centímetro":
                unidade = " cm";
                break;
            case "Milímetro":
                unidade = " mm";
                break;
                
        }
        resultado.setText(result+unidade);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        varDe.setSelectedItem("Quilômetro");
        varPara.setSelectedItem("Quilômetro");
        num.setText("");
        resultado.setText("Resultado");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField num;
    private javax.swing.JLabel resultado;
    private javax.swing.JComboBox<String> varDe;
    private javax.swing.JComboBox<String> varPara;
    // End of variables declaration//GEN-END:variables
}
